<?php

/**
 * @file
 * Define the function relative to the inherit product.
 */



/*****************************************************************
*
*    MODULE
*
*****************************************************************/

/**
 * Implements hook_menu().
 * Add an ajax callback.
 */
function wikicompare_inherit_product_menu() {

  $items = array();

  $items['compute_inherit_callback'] = array(
    'page callback' => 'compute_inherit_response',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'ajax_deliver',
  );

  return $items;

}



/**
 * Ajax callback function called by javascript.
 *
 * @param $method
 *   Indicate if the call was made with javascript or if it's a simple browser call.
 *
 * @param $POST
 *   The variables send by the javascript.
 *
 * @return $page
 *   Array containing the instructions for the javascript.
 */
function compute_inherit_response($method = 'ajax') {

  //If javascript isn't activated on the browser, the first argument will not be transformed in ajax value. In such case, we just redirect to an error message.
  if ($method != 'ajax') {
    $output = NOJS_MESSAGE;
    return $output;
  }

  $commands = array();
  $support = 0;

  if ($_POST['use_from_inherit'] == 'true') {

    $inherit_id = NULL;

    $query = db_select('cache_evaluation', 'n');
    $query->addField('c', 'inherit_product_id', 'inherit_id');
    $query->addField('ci', 'support', 'support');
    $query->leftjoin('cache_product', 'c', 'n.product_id = c.nid');
    $query->leftjoin('cache_evaluation', 'ci', 'c.inherit_product_id = ci.product_id AND ci.feature_id = n.feature_id');
    $query->condition('n.nid', $_POST['nid']);
    $result = $query->execute();
    foreach ($result as $record) {
      $inherit_id = $record->inherit_id;
      $support = $record->support;
    }

    if ($inherit_id != NULL) {
      if ($support) {
        $commands[] = ajax_command_invoke('#edit-wikicompare-support-und', 'attr', array('checked', 'checked'));
      } else {
        $commands[] = ajax_command_invoke('#edit-wikicompare-support-und', 'removeAttr', array('checked'));
      }
      $commands[] = ajax_command_invoke('#edit-wikicompare-support-und', 'attr', array('disabled', 'disabled'));
    }

  } else {
    $query = db_select('cache_evaluation', 'n');
    $query->addField('n', 'support', 'support');
    $query->condition('n.nid', $_POST['nid']);
    $result = $query->execute();
    foreach ($result as $record) {
      $support = $record->support;
    }

    if ($support) {
      $commands[] = ajax_command_invoke('#edit-wikicompare-support-und', 'attr', array('checked', 'checked'));
    } else {
      $commands[] = ajax_command_invoke('#edit-wikicompare-support-und', 'removeAttr', array('checked'));
    }
    $commands[] = ajax_command_invoke('#edit-wikicompare-support-und', 'removeAttr', array('disabled'));

  }

  $page = array('#type' => 'ajax', '#commands' => $commands);
  return $page;

}





/*****************************************************************
*
*    CORE_FUNCTIONS
*
*****************************************************************/

/**
 * Update the main query of wikicompare_update_compare_tree to add some fields we will need later.
 *
 * @param $query
 *   The query to update. Passed by reference.
 */
function wikicompare_inherit_product_update_main_query(&$query) {

  $query->addField('n', 'use_from_inherit', 'use_from_inherit');
  //Recover the percent value of the inherited evaluation
  $query->addField('ni', 'product_id', 'inheriting_product_id');
  $query->addField('ni', 'nid', 'inheriting_evaluation_nid');
  $query->addField('ni', 'percent', 'inheriting_evaluation_cache_percent');
  $query->addField('ni', 'css_class', 'inheriting_evaluation_cache_css_class');
  $query->leftjoin('cache_evaluation', 'ni', 'n.parent_through_inherit_id = ni.nid');

}



/**
 * Prepare the variables before the node computation.
 * Essentially check if we have the percent of the inherited evaluation and recover the children through inherit we will update after the computation.
 *
 * @param $nodes
 *   The object returned by the initial sql request, that we need to complete. Passed by reference.
 *
 * @param type
 *   The type of the nids update by update_compare_tree function.
 *
 * @param $nids
 *   The nids of the nodes to update.
 */
function wikicompare_inherit_product_update_comparative_table_preparation(&$nodes, $type, $nids) {

    //Mark to update the inherited evaluation without cache percent
    $to_update = array();
    foreach($nodes as $node) {
      if ($node->inheriting_product_id) {
        if (!$node->inheriting_evaluation_cache_percent) {
          $to_update[$node->inheriting_evaluation_nid] = $node->inheriting_evaluation_nid;
        }
      }
    }

    //Recover the missing cache percent
    if (!empty($to_update)) {
      //There is a danger here if the inherited product are looping. Later, we have to think about adding a security when we insert/update the inherit field of a product which check if there is a loop. There is a security in the interface (in select popin) but not in this update code.
      $res = wikicompare_update_compare_tree('evaluation', $to_update);
      foreach($nodes as $node) {
        if (isset($res[$node->inheriting_evaluation_nid])) {
          $node->inheriting_evaluation_cache_percent = $res[$node->inheriting_evaluation_nid]['percent'];
          $node->inheriting_evaluation_cache_css_class = $res[$node->inheriting_evaluation_nid]['css_class'];
        }
      }
    }

    $through_inherit_childs = array();
    if (in_array($type, array('product', 'evaluation')) && !empty($nids))  {
      $query = db_select('cache_evaluation', 'n');
      $query->addField('n', 'nid', 'nid');
      $query->addField('n', 'feature_id', 'fid');
      $query->addField('nc', 'inherit_product_id', 'inherit_product_id');
      $query->join('cache_product', 'nc', 'n.product_id = nc.nid');
      //Only the evaluation which has no children on both axis will be updated because only them can have their percent updated by inheritance
      $query->condition('n.product_has_children', 0);
      $query->condition('n.feature_has_children', 0);
      switch ($type) {
        case "product":
          $query->condition('nc.inherit_product_id', $nids, 'IN');
          break;
        default:
          $query->condition('parent_through_inherit_id', $nids, 'IN');
          break;
      }
      $result = $query->execute();

      foreach($result as $record) {
        //We assign the children evaluation in a array with fid and cid as key so their parents can recover them with fid and cid key
        $through_inherit_childs[$record->fid][$record->inherit_product_id][$record->nid] = $record;
      }
    }

    //Assign children to each node to compute.
    foreach($nodes as $node) {
      $node->through_inherit_childs = array();
      if (isset($through_inherit_childs[$node->fid][$node->cid])) {
        //Assign the children thanks to fid and cid key
        $node->through_inherit_childs = $through_inherit_childs[$node->fid][$node->cid];
      }
    }

}



/**
 * Return the data computed according to the inherited evaluation.
 *
 * @param $node
 *   The node to compute. Passed by reference.
 */
function wikicompare_inherit_product_from_other_support(&$node) {

  //Work only if the product of the evaluation inherit a node and we didn't override the information in the evaluation.
  if ($node->inheriting_product_id && $node->use_from_inherit) {
    $node->percent = $node->inheriting_evaluation_cache_percent;
    $node->css_class = $node->inheriting_evaluation_cache_css_class;
  }

}



/**
 * Add in the evaluation to update the evaluation which inherit the current evaluation.
 *
 * @param $to_update
 *   The array containing the evaluation which will be updated by the recursive function. Passed by reference.
 *
 * @param $node
 *   The node we are currently checking.
 */
function wikicompare_inherit_product_update_comparative_table_post(&$to_update, $node) {

  if (!empty($node->through_inherit_childs)) {
    //Add all inheriting children in the nodes to update list.
    foreach($node->through_inherit_childs as $child) {
      $to_update[$child->nid] = $child->nid;
    }
  }

}



/**
 * Search for the inhehrit product specific fields in the flush tables function.
 *
 * @param $query
 *   The query to update. Passed by reference.
 *
 * @param $type
 *   The type of the nodes we are searching for.
 */
function wikicompare_inherit_product_flush_select(&$query, $type) {

  if ($type == 'product') {
    $query->addField('nic', 'wikicompare_inherit_product_id_target_id', 'inherit_product_id');
    $query->leftjoin('field_revision_wikicompare_inherit_product_id', 'nic', 'n.vid = nic.revision_id');
  }

  if ($type == 'evaluation') {
    $query->addField('nu', 'wikicompare_use_from_inherit_value', 'use_from_inherit');
    $query->leftjoin('field_revision_wikicompare_use_from_inherit', 'nu', 'n.vid = nu.revision_id');
  }

}



/**
 * Prepare the inherit product specific fields in the flush tables function.
 *
 * @param $to_insert
 *   Array containing the data of the record which will be inserted. Passed by reference.
 *
 * @param $record
 *   The record we are currently checking
 *
 * @param $type
 *   The type of the node
 */
function wikicompare_inherit_product_flush_cache(&$to_insert, $record, $type) {

  if ($type == 'product') {
    $to_insert[$record->nid]['inherit_product_id'] = $record->inherit_product_id;
  }

  if ($type == 'evaluation') {
    $use_from_inherit = 1;
    if ($record->use_from_inherit != NULL) {
      $use_from_inherit = $record->use_from_inherit;
    }
    $to_insert[$record->nid]['use_from_inherit'] = $use_from_inherit;
  }
}



/**
 * Add inherit product specific fields in db request.
 *
 * @param $query
 *   The query to update. Passed by reference.
 *
 * @param $type
 *   The type of the request.
 */
function  wikicompare_inherit_product_request_db(&$query, $type) {

  if ($type == 'product') {
    $query->addField('n', 'inherit_product_id', 'inherit_product_id');
  }

  if ($type == 'evaluation') {
    $query->addField('n', 'use_from_inherit', 'use_from_inherit');
  }

}





/*****************************************************************
*
*    NODES
*
*****************************************************************/

/**
 * Prepare the inherit product specific field to insert in wikicompare cache tables.
 *
 * @param $fields
 *   The fields prepared in generic function. Passed by reference.
 *
 * @param $type
 *   The type of the created node.
 *
 * @param $node
 *   The created node.
 */
function wikicompare_inherit_product_cache_insert_fields(&$fields, $type, $node) {

  //Product specific field.
  if ($type == 'product') {

    //Insert the inherit product field in the prepared data.
    $inherit_product_id = NULL;
    if (isset($node->wikicompare_inherit_product_id['und'][0])) {
      $inherit_product_id = $node->wikicompare_inherit_product_id['und'][0]['target_id'];
    }
    $fields['inherit_product_id'] = $inherit_product_id;

  }

}



/**
 * Prepare the inherit product specific field to insert in evaluation object.
 *
 * @param $node_evaluation
 *   The evaluation node which will be created. Passed by reference.
 */
function wikicompare_inherit_product_insert_evaluation(&$node_evaluation) {

  //We set the value of use_from_inherit to 1 because, without user action, it must use the value of the inherited product.
  $node_evaluation->wikicompare_use_from_inherit['und'][0]['value'] = 1;

}



/**
 * Prepare the inherit product specific field to insert in evaluation cache table.
 *
 * @param $cache_evaluation
 *   The evaluation fields which will be inserted in table. Passed by reference.
 *
 * @param $node
 *   The evaluation node which was created.
 */
function wikicompare_inherit_product_cache_evaluation_fields(&$cache_evaluation, $node) {

  //Insert the use_from_inherit field from the created objet.
  $cache_evaluation['use_from_inherit'] = $node->wikicompare_use_from_inherit['und'][0]['value'];

}



/**
 * Update parent_through_inherit_id in cache_evaluation.
 *
 * @param $node
 *   The node which was created.
 */
function wikicompare_inherit_product_insert_parent_inherit($node) {

  if ($node->type == 'product') {
    if (isset($node->wikicompare_inherit_product_id['und'][0])) {
      wikicompare_inherit_product_update_parent_link($node->nid);
    }
  }

}



/**
 * Prepare the header for the mass insert in wikicompare cache table with the inherit product specific fields.
 *
 * @param $header
 *   The header array to modify. Passed by reference.
 *
 * @param $type
 *   The type of record which will be cached.
 */
function wikicompare_inherit_product_cache_fields_header(&$header, $type) {

  //Product specific field.
  if ($type == 'product') {
    $header[] = 'inherit_product_id';
  }

  //evaluation specific field.
  if ($type == 'evaluation') {
    $header[] = 'use_from_inherit';
  }

}



/**
 * Update cache so all inherited children are now without inherit product.
 *
 * @param $node
 *   The deleted node.
 */
function wikicompare_inherit_product_cache_product_delete($node) {

  if ($node->type == 'product') {

    //Get the product which was inheriting the deleted node.
    $to_update = array();
    $query = db_select('cache_product', 'c');
    $query->addField('c', 'nid', 'nid');
    $query->condition('c.inherit_product_id', $node->nid);
    $result = $query->execute();
    foreach($result as $record) {
      $to_update[$record->nid] = $record->nid;
    }

    if (!empty($to_update)) {
      //Update the children so they no more inherit any node.
      db_update('cache_product')
        ->fields(array(
          'inherit_product_id' => NULL,
        ))
        ->condition('nid', $to_update, 'IN')
        ->execute();

      //We launch the tree update on the old children.
      wikicompare_update_compare_tree('product', $to_update);
    }

  }

}



/**
 * Trigger a tree update if the inherit_product_id field has changed.
 *
 * @param $to_update
 *   The array containing the id which will trigger a tree update. Passed by reference.
 *
 * @param $node_revision
 *   The object containing the new data of the node.
 *
 * @param $current_node
 *   The object containing the old data of the node.
 */
function wikicompare_inherit_product_preupdate_product(&$to_update, $node_revision, $current_node) {

  if ($node_revision->type == 'product') {
    //Get inherit_id.
    $node_revision_inherit = NULL;
    if ($node_revision->wikicompare_inherit_product_id) {
      $node_revision_inherit = $node_revision->wikicompare_inherit_product_id['und'][0]['target_id'];
    }
    $current_node_inherit = NULL;
    if ($current_node->wikicompare_inherit_product_id) {
      $current_node_inherit = $current_node->wikicompare_inherit_product_id['und'][0]['target_id'];
    }

    //Trigger a tree update on the updated node because the value of his evaluations may have changed.
    if ($node_revision_inherit != $current_node_inherit) {
      $to_update[$node_revision->nid] = $node_revision->nid;

      //Mark the modified node so his evaluations will be updated with his new evaluations parents through inherit.
      db_update('cache_product')
        ->fields(array(
          'inherit_changed' => 1,
        ))
        ->condition('nid', $node_revision->nid)
        ->execute();

    }
  }

}



/**
 * Trigger a tree update if the use_from_inherit field has changed.
 *
 * @param $to_update
 *   The array containing the id which will trigger a tree update. Passed by reference.
 *
 * @param $node_revision
 *   The object containing the new data of the node.
 *
 * @param $current_node
 *   The object containing the old data of the node.
 */
function wikicompare_inherit_product_preupdate_evaluation(&$to_update, $node_revision, $current_node) {

  if ($node_revision->wikicompare_use_from_inherit['und'][0]['value'] != $current_node->wikicompare_use_from_inherit['und'][0]['value']) {
    $to_update[$node_revision->nid] = $node_revision->nid;
  }

}



/**
 * Add the inherit product module specific field in the data which will update the wikicompare cache.
 *
 * @param $fields
 *   The array containing the fields which will update the cache. Passed by reference.
 *
 * @param $node_revision
 *   The object containing the new data of the node.
 */
function wikicompare_inherit_product_cache_update_fields(&$fields, $node_revision) {

  //Product specific field.
  if ($node_revision->type == 'product') {
    $inherit_id = NULL;
    if (isset($node_revision->wikicompare_inherit_product_id['und'][0])) {
      $inherit_id = $node_revision->wikicompare_inherit_product_id['und'][0]['target_id'];
    }
    $fields['inherit_product_id'] = $inherit_id;
  }
  //evaluation specific field.
  if ($node_revision->type == 'evaluation') {
    $fields['use_from_inherit'] = $node_revision->wikicompare_use_from_inherit['und'][0]['value'];
  }

}



/**
 * Update the query to get inherit_changed flag.
 *
 * @param $query
 *   The query we want to modify. Passed by reference.
 *
 * @param $type
 *   The type of the modified node.
 */
function wikicompare_inherit_product_get_inherit_changed(&$query, $type) {

  if ($type == 'product') {
    $query->addField('n', 'inherit_changed', 'inherit_changed');
  }

}



/**
 * Update the parent_through_inherit fields in evaluation.
 *
 * @param $node
 *   The updated node.
 *
 * @param $type
 *   The type of the node.
 */
function wikicompare_inherit_product_update_parent_evaluations($node, $type) {

  if ($type == 'product') {
    if ($node->inherit_changed) {
      wikicompare_inherit_product_update_parent_link($node->nid);
      db_update('cache_product')
        ->fields(array(
          'inherit_changed' => 0
        ))
        ->condition('nid', $node->nid)
        ->execute();
    }
  }

}



/**
 * Function which will update the parent though inherit field in cache_evaluation. This field is important for the percentage computation.
 *
 * @param $nid
 *   The nid of the product or feature which we need to update the evaluation. If empty, all evaluation will be updated.
 */
function wikicompare_inherit_product_update_parent_link($nid=NULL) {

  if (Database::getConnection()->databaseType() == 'mysql') {
    $query = 'UPDATE cache_evaluation n
           INNER JOIN cache_product nc ON n.product_id = nc.nid
           LEFT JOIN cache_evaluation nci ON (nc.inherit_product_id = nci.product_id AND n.feature_id = nci.feature_id)
           SET n.parent_through_inherit_id = nci.nid';
    if ($nid != NULL) {
      $query = $query . ' WHERE nc.nid = ' . $nid;
    }
  } else {
    $query = 'UPDATE cache_evaluation
           SET parent_through_inherit_id = nci.nid
           FROM cache_evaluation n
           INNER JOIN cache_product nc ON n.product_id = nc.nid
           LEFT JOIN cache_evaluation nci ON (nc.inherit_product_id = nci.product_id AND n.feature_id = nci.feature_id)
           WHERE cache_evaluation.nid = n.nid';
    if ($nid != NULL) {
      $query = $query . ' AND nc.nid = ' . $nid;
    }
  }

  db_query($query);

}





/*****************************************************************
*
*    FORM
*
*****************************************************************/

/**
 * Add the fields relative to inherit product in product node.
 *
 * @param $form
 *   The form array which will be used by Drupal to build the node form. Passed by reference.
 *
 * @param $output
 *   The HTML code which will be inserted. Passed by reference
 *
 * @param $form_type
 *   Flag defining if the function is called to build a form node of a fastaction form.
 *
 * @param $type
 *   The type of the consulted node.
 *
 * @param $node
 *   Object containing the detail of the node.
 *
 * @param $readonly
 *   Flag indicated if the user can modify the node.
 */
function wikicompare_inherit_product_modify_form_no_evaluation(&$form, &$output, $form_type, $type, $node, $nid, $readonly) {

  //Product specific field.
  if ($type == 'product') {

    $inherit_id = 0;
    //Default message.
    $title = 'No inherited product';
    //Get inherited node detail.
    if (isset($node->wikicompare_inherit_product_id['und'])) {
      $inherit_id = $node->wikicompare_inherit_product_id['und'][0]['target_id'];
      //We use wikicompare_build_recursive_data() to build the full title of the inherited node.
      $res = wikicompare_build_recursive_data('product', array($inherit_id), wikicompare_initialize_settings());
      $title = $res['data'][$inherit_id]['data']->fulltitle;
    }

    //Link which will open a popin where we can select the inherited node.
    $select_inherit_link = array(
      'text' => 'Select inherited product',
      'title' => 'Select inherited product',
      'selector' => 'dialog-content',
      'path' => 'wikicompare_get_dialog_callback/selectdialog/product/wikicompare-inherit-product-id/' . $nid,
    );
    //Link which will reset the parent.
    $clear_inherit_link = l('Clear', '/',  array('attributes' => array('class' => array('clear_link_inherit'), 'type' => $type)));

    //Add an array which will be generated by drupal with the items relatives to the inherited.
    if ($form_type == 'form') {
      //Container which will contain the inherited name.
      $form['container_selected_inherit'] = array(
        'title' => array('#markup' => $title),
        '#type' => 'container',
        '#id' => 'container-wikicompare-inherit-product-id',
        '#weight' => -3,
         //We add the link after the container.
        '#suffix' => '<p>' . theme('simple_dialog_link', $select_inherit_link) . ' ' . $clear_inherit_link . '</p>'
      );
      //Hide the field from drupal. We can't use the hide() function because it'll block the javascript to update the inherited node.
      $form['wikicompare_inherit_product_id']['#attributes']['style'] = 'display:none;';
    }

    //Add the HTML code relative to the inherited node.
    if ($form_type == 'fastaction') {
      //Container with the inherited name.
      $output .= '<p><span id="container-wikicompare-inherit-product-id">' . $title . '</span>';
      if ($readonly != True) {
        //Span with the inherit_id, which will be recovered by the submit function and updated by javascript. Followed by the link.
        $output .= '<span id="wikicompare-inherit-product-id" style="display:none;">' . $inherit_id . '</span> ' . theme('simple_dialog_link', $select_inherit_link) . ' ' . $clear_inherit_link . '</p>';
      }
    }

  }

}



/**
 * Add the fields relative to inherit product in evaluation node.
 *
 * @param $form
 *   The form array which will be used by Drupal to build the node form. Passed by reference.
 *
 * @param $output
 *   The HTML code which will be inserted. Passed by reference
 *
 * @param $disable_support
 *   Flag indicated if the support field can be modified. Passed by reference.
 *
 * @param $test
*   Test if the support field must be checked by default. Passed by reference.
 *
 * @param $form_type
 *   Flag defining if the function is called to build a form node of a fastaction form.
 *
 * @param $type
 *   The type of the consulted node.
 *
 * @param $node
 *   Object containing the detail of the node.
 *
 * @param $readonly
 *   If the user have right to modify fields.
 *
 * @param $fastaction
 *   The fastaction (add or edit)
 */
function wikicompare_inherit_product_modify_form_evaluation(&$form, &$output, &$disable_support, &$test, $form_type, $type, $node, $readonly, $fastaction) {

  if ($type == 'evaluation') {

    //Get details of the inherited evaluation.
    $query = db_select('cache_evaluation', 'n');
    $query->addField('c', 'inherit_product_id', 'inherit_id');
    $query->addField('c', 'has_children', 'product_has_children');
    $query->addField('f', 'has_children', 'feature_has_children');
    $query->addField('ci', 'support', 'inherit_support');
    $query->leftjoin('cache_product', 'c', 'n.product_id = c.nid');
    $query->leftjoin('cache_feature', 'f', 'n.feature_id = f.nid');
    $query->leftjoin('cache_evaluation', 'ci', 'c.inherit_product_id = ci.product_id AND n.feature_id = ci.feature_id');
    $query->condition('n.nid', $node->nid);
    $result = $query->execute();
    foreach ($result as $record) {
      $res = $record;
    }

    if ($form_type == 'form') {

      //If there is no inherited product or if we are not at the root of the tree, we don't need the use_from_inherit field.
      if ($res->inherit_id == NULL || $res->product_has_children || $res->feature_has_children) {
        hide($form['wikicompare_use_from_inherit']);
      } else {

        //Hidden link which will refresh in ajax the data when we click on use_from_inherit checkbox.
        $reset_link = array(
          '#type' => 'link',
          '#title' => 'compute inherit',
          '#href' => 'compute_inherit_callback/nojs',
          '#id' => 'compute_inherit_link_' . $node-> nid,
          '#attributes' => array(
            'class' => array('compute_inherit_link'),
            'style' => 'display:none',
          ),
        );
        //Add the link after the Drupal field.
        $form['wikicompare_use_from_inherit']['und']['#suffix'] = render($reset_link);
        //If use_from_inherit is checked at the generation of the form, then the value of support field if the value of the inherited evaluation.
        if ($form['wikicompare_use_from_inherit']['und']['#default_value'] == 1) {
          $form['wikicompare_support']['und']['#default_value'] = $res->inherit_support;
          $form['wikicompare_support']['und']['#disabled'] = True;
        }
      }

      //Move use_from_inherit before support field.
      $form['wikicompare_use_from_inherit']['#weight'] = -2;

    }

    if ($form_type == 'fastaction') {

      if ($res->inherit_id != NULL) {
        //I wasn't able to use the renderable array, so I coded directly in html.
        $output .= '<input class="form_evaluation_fastaction_inherit form-checkbox" type="checkbox" id="edit-wikicompare-use-from-inherit-und"';

        //Recover value from database.
        if ($fastaction == 'edit') {
          if ($node->wikicompare_use_from_inherit['und'][0]['value'] == 1) {
            $output .= ' checked="checked"';
            $test = True;
          }
        }

        //If the user do not have rights on the node.
        if ($readonly == True) {
          $output .= ' disabled="disabled"';
        }

        //Hidden link which will refresh in ajax the data when we click on use_from_inherit checkbox.
        $reset_link = array(
          '#type' => 'link',
          '#title' => 'compute inherit',
          '#href' => 'compute_inherit_callback/nojs',
          '#id' => 'compute_inherit_link_' . $node-> nid,
          '#attributes' => array(
            'class' => array('compute_inherit_link'),
            'style' => 'display:none',
          ),
        );

        $output .= ' value="1" />' . render($reset_link) . '<label class="option" for="form_evaluation_fastaction_usefrominherit_' . $node->nid . '">Use from inherit? </label>';

        //Disable the support field located after this one
        if ($node->wikicompare_use_from_inherit['und'][0]['value'] == 1) {
          $disable_support = True;
        }
      }

    }

  }

}



/**
 * Test if the support field must be checked.
 *
 * @param $test_support
 *   If this test is True, the support field will be checked. Passed by reference.
 *
 * @param $test
 *   Boolean indicated that the value of the inherited evaluation must be used.
 *
 * @param $node
 *   Object containing the detail of the node.
 */
function wikicompare_inherit_product_test_form_evaluation(&$test_support, $test, $node) {

  //If we have to use the value from inherited evaluation.
  if ($test == True) {

    //Get inherited evaluation details .
    $query = db_select('cache_evaluation', 'n');
    $query->addField('c', 'inherit_product_id', 'inherit_id');
    $query->addField('c', 'has_children', 'product_has_children');
    $query->addField('f', 'has_children', 'feature_has_children');
    $query->addField('ci', 'support', 'inherit_support');
    $query->leftjoin('cache_product', 'c', 'n.product_id = c.nid');
    $query->leftjoin('cache_feature', 'f', 'n.feature_id = f.nid');
    $query->leftjoin('cache_evaluation', 'ci', 'c.inherit_product_id = ci.product_id AND n.feature_id = ci.feature_id');
    $query->condition('n.nid', $node->nid);
    $result = $query->execute();
    foreach ($result as $record) {
      if ($record->inherit_support) {
        $test_support = True;
      //The else because in any case, the inherited override the previous value
      } else {
        $test_support = False;
      }
    }

  }

}



/**
 * Remove important inherit product fields from translated node.
 *
 * @param $form
 *   The form array which will be used by Drupal to build the node form. Passed by reference.
 *
 * @param $form_state
 *   Array containing in-depth information of the node and form settings. Passed by reference.
 *
 * @param $node
 *   Object containing the detail of the node.
 */
function wikicompare_inherit_product_wikicompare_translation_form(&$form, &$form_state, $node) {

  if (isset($form['wikicompare_inherit_product_id'])) {
    $form['container_selected_inherit'] = $form['container_selected_inherit']['title'];
    unset($form['wikicompare_inherit_product_id']);
    unset($form_state['node']->wikicompare_inherit_product_id);
  }

}





/*****************************************************************
*
*    FASTACTION
*
*****************************************************************/

/**
 * Assign inherit product specific fields.
 *
 * @param $node
 *   The node which will be submitted. Passed by reference.
 *
 * @param $donotupdate
 *   Boolean indicated if the support field must be updated later. Passed by reference.
 *
 * @param $POST
 *   Variables from javascript.
 */
function wikicompare_inherit_product_fastaction_submit_element(&$node, &$donotupdate,  $POST) {

  //Product specific fields.
  if ($node->type == 'product') {
    if ($POST['inherit_id'] != 0) {
          $node->wikicompare_inherit_product_id['und'][0]['target_id'] = $POST['inherit_id'];
          $node->wikicompare_inherit_product_id['und'][0]['target_type'] = "node";

    } else {
          $node->wikicompare_inherit_product_id['und'] = NULL;
    }
  }

  //evaluation specific fields.
  if ($node->type == 'evaluation') {
    if ($POST['use_from_inherit'] == 'true') {
      $node->wikicompare_use_from_inherit['und'][0]['value'] = 1;
      //If we use from the inherited evaluation, then we do not update the support field of the node.
      $donotupdate = True;
    } else {
      $node->wikicompare_use_from_inherit['und'][0]['value'] = 0;
    }
  }

}





/*****************************************************************
*
*    GENERATE DEMO
*
*****************************************************************/

/**
 * Export inherit product.
 *
 * @param $output
 *   The html code of the export. Passed by reference.
 */
function wikicompare_inherit_product_demo_export(&$output) {

  $query = db_select('cache_product', 'n');
  $query->addField('n', 'nid', 'nid');
  $query->addField('n', 'inherit_product_id', 'inherit_product_id');
  $query->where("n.inherit_product_id IS NOT NULL");
  $result = $query->execute();

  foreach ($result as $record) {

    $output .= "<p>if (module_exists('wikicompare_inherit_product')) {</p>";

    $output .= "<p>\$node = node_load(\$products['new-" . $record->nid . "']);<br/>";
    $output .= "\$node->wikicompare_inherit_product_id['und'][0]['target_id'] = \$products['new-" . $record->inherit_product_id . "'];<br/>";
    $output .= "\$node->wikicompare_inherit_product_id['und'][0]['target_type'] = 'node';<br/>";
    $output .= "\$node->promote = 0;<br/>";
    $output .= "\$node->sticky = 0;<br/>";
    $output .= "\$node->revision = TRUE;<br/>";
    $output .= "\$node->revision_moderation = TRUE;<br/>";
    $output .= "node_save(\$node);<br/>";
    $output .= "_revisioning_publish_latest_revision(\$node);</p>";

    $output .= "<p>}</p>";

  }

}



/**
 * Modify sql request of the evaluation export.
 *
 * @param $query
 *   The evaluation query. Passed by reference.
 */
function wikicompare_inherit_product_demo_export_evaluation_request(&$query) {
  $query->addField('n', 'use_from_inherit', 'use_from_inherit');
  $query->where('n.support = 1 OR (n.use_from_inherit = 0 AND c.inherit_product_id IS NOT NULL)');
}



/**
 * Export evaluation specific fields.
 *
 * @param $output
 *   The html code of the export. Passed by reference.
 *
 * @param $record
 *   The record we are currently exporting.
 */
function wikicompare_inherit_product_demo_export_evaluation_render(&$output, $record) {
  $output .= "if (module_exists('wikicompare_inherit_product')) {<br/>";
  $output .= "\$node->wikicompare_use_from_inherit['und'][0]['value'] = " . $record->use_from_inherit . ";<br/>";
  $output .= "}<br/>";
}




/**
 * Display inherit product specific fields in the generate demo form.
 *
 * @param $form
 *   The generate demo form. Passed by reference.
 */
function wikicompare_inherit_product_demo_form(&$form) {

  $form['demo_fieldset']['product_inherit_chance'] = array(
    '#type' => 'textfield',
    '#title' => t('Chance that a product inherit another one (1/x)'),
    '#default_value' => 5,
    '#size' => 3,
    '#maxlength' => 3,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_integer_positive_or_null'),
  );

  $form['demo_fieldset']['evaluation_use_from_inherit_chance'] = array(
    '#type' => 'textfield',
    '#title' => t('Chance that a evaluation which inherit another one use his own value (1/x)'),
    '#default_value' => 5,
    '#size' => 3,
    '#maxlength' => 3,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_integer_positive_or_null'),
  );

}



/**
 * Generate inherit product demo data.
 *
 * @param $form_state
 *   The values submitted by the form.
 *
 * @param $products_created
 *   The nid of the product created by the function.
 */
function wikicompare_inherit_product_demo_submit_generate($form_state, $products_created) {

  if (!empty($products_created) && $form_state['input']['product_inherit_chance'] != 0) {

    $product_without_children = array();
    $query = db_select('cache_product', 'c');
    $query->addField('c', 'nid', 'nid');
    $query->condition("c.has_children", 0);
    $result = $query->execute();
    foreach ($result as $record) {
      $product_without_children[$record->nid] = $record->nid;
    }

    foreach ($product_without_children as $cid) {
      if (rand(1, $form_state['input']['product_inherit_chance']) == $form_state['input']['product_inherit_chance']) {
        $inherit_product_id = 0;
        while ($inherit_product_id == 0 || $inherit_product_id == $cid) {
          $inherit_product_id = array_rand($product_without_children);
        }

        $node = node_load($cid);
        $node->wikicompare_inherit_product_id['und'][0]['target_id'] = $inherit_product_id;
        $node->wikicompare_inherit_product_id['und'][0]['target_type'] = "node";

        $node->promote = 0;
        $node->sticky = 0;
        $node->revision = TRUE;
        $node->revision_moderation = TRUE;

        node_save($node);

        _revisioning_publish_latest_revision($node);

        //Security against loop, we don't want that two product inherit each other
        unset($product_without_children[$cid]);

      }
    }

  }

}



/**
 * Modify evaluation query.
 *
 * @param $query
 *   The implementatio query.
 */
function wikicompare_inherit_product_demo_submit_evaluation_query(&$query) {
  $query->addField('c', 'inherit_product_id', 'inherit_product_id');
}



/**
 * Modify inherit product specific field.
 *
 * @param $node
 *   The node we are modifying.
 *
 * @param $modified
 *   Flag indicated that the node was modified.
 *
 * @param $form_state
 *   The values submitted by the form.
 *
 * @param $record
 *   The detail of the evaluation.
 */
function wikicompare_inherit_product_demo_submit_evaluation(&$node, &$modified, $form_state, $record) {

  if (($record->inherit_product_id != NULL) && (rand(1, $form_state['input']['evaluation_use_from_inherit_chance']) == $form_state['input']['evaluation_use_from_inherit_chance'])) {
    $node->wikicompare_use_from_inherit['und'][0]['value'] = 0;
    $modified = True;
  }

}

?>
